ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) 
    ESX = obj 
end)

ESX.RegisterServerCallback('Get:UserGroup', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)
	local group = xPlayer.getGroup()
	print(GetPlayerName(source).." - "..group)
    cb(group)
end)

RegisterNetEvent('Weapon:GiveAllWeapons')
AddEventHandler('Weapon:GiveAllWeapons', function()
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(source)
    -- Arme de mélée
    xPlayer.addWeapon('weapon_dagger', 9999)
    xPlayer.addWeapon('weapon_bat', 9999)
    xPlayer.addWeapon('weapon_bottle', 9999)
    xPlayer.addWeapon('weapon_crowbar', 9999)
    xPlayer.addWeapon('weapon_unarmed', 9999)
    xPlayer.addWeapon('weapon_flashlight', 9999)
    xPlayer.addWeapon('weapon_golfclub', 9999)
    xPlayer.addWeapon('weapon_hammer', 9999)
    xPlayer.addWeapon('WEAPON_dagger', 9999)
    xPlayer.addWeapon('WEAPON_bottle', 9999)
    xPlayer.addWeapon('WEAPON_golfclub', 9999)
    xPlayer.addWeapon('WEAPON_hammer', 9999)
    xPlayer.addWeapon('weapon_hatchet', 9999)
    xPlayer.addWeapon('weapon_knuckle', 9999)
    xPlayer.addWeapon('weapon_knife', 9999)
    xPlayer.addWeapon('weapon_machete', 9999)
    xPlayer.addWeapon('weapon_switchblade', 9999)
    xPlayer.addWeapon('weapon_nightstick', 9999)
    xPlayer.addWeapon('weapon_wrench', 9999)
    xPlayer.addWeapon('weapon_battleaxe', 9999)
    xPlayer.addWeapon('weapon_poolcue', 9999)
    xPlayer.addWeapon('weapon_stone_hatchet', 9999)
    -- Handguns
    xPlayer.addWeapon('weapon_pistol', 9999)
    xPlayer.addWeapon('weapon_pistol_mk2', 9999)
    xPlayer.addWeapon('weapon_combatpistol', 9999)
    xPlayer.addWeapon('weapon_appistol', 9999)
    xPlayer.addWeapon('weapon_stungun', 9999)
    xPlayer.addWeapon('weapon_pistol50', 9999)
    xPlayer.addWeapon('weapon_snspistol', 9999)
    xPlayer.addWeapon('weapon_snspistol_mk2', 9999)
    xPlayer.addWeapon('weapon_heavypistol', 9999)
    xPlayer.addWeapon('weapon_vintagepistol', 9999)
    xPlayer.addWeapon('weapon_flaregun', 9999)
    xPlayer.addWeapon('weapon_marksmanpistol', 9999)
    xPlayer.addWeapon('weapon_revolver', 9999)
    xPlayer.addWeapon('weapon_revolver_mk2', 9999)
    xPlayer.addWeapon('weapon_doubleaction', 9999)
    xPlayer.addWeapon('weapon_raypistol', 9999)
    xPlayer.addWeapon('weapon_ceramicpistol', 9999)
    xPlayer.addWeapon('weapon_navyrevolver', 9999)
    xPlayer.addWeapon('weapon_gadgetpistol', 9999)
    xPlayer.addWeapon('weapon_stungun_mp', 9999)
    -- Submachine Guns
    xPlayer.addWeapon('weapon_microsmg', 9999)
    xPlayer.addWeapon('weapon_smg', 9999)
    xPlayer.addWeapon('weapon_smg_mk2', 9999)
    xPlayer.addWeapon('weapon_assaultsmg', 9999)
    xPlayer.addWeapon('weapon_combatpdw', 9999)
    xPlayer.addWeapon('weapon_machinepistol', 9999)
    xPlayer.addWeapon('weapon_minismg', 9999)
    xPlayer.addWeapon('weapon_raycarbine', 9999)
    -- Shotguns
    xPlayer.addWeapon('weapon_pumpshotgun', 9999)
    xPlayer.addWeapon('weapon_pumpshotgun_mk2', 9999)
    xPlayer.addWeapon('weapon_sawnoffshotgun', 9999)
    xPlayer.addWeapon('weapon_assaultshotgun', 9999)
    xPlayer.addWeapon('weapon_bullpupshotgun', 9999)
    xPlayer.addWeapon('weapon_musket', 9999)
    xPlayer.addWeapon('weapon_heavyshotgun', 9999)
    xPlayer.addWeapon('weapon_dbshotgun', 9999)
    xPlayer.addWeapon('weapon_autoshotgun', 9999)
    xPlayer.addWeapon('weapon_combatshotgun', 9999)
    -- Assault Rifles
    xPlayer.addWeapon('weapon_assaultrifle', 9999)
    xPlayer.addWeapon('weapon_assaultrifle_mk2', 9999)
    xPlayer.addWeapon('weapon_carbinerifle', 9999)
    xPlayer.addWeapon('weapon_carbinerifle_mk2', 9999)
    xPlayer.addWeapon('weapon_advancedrifle', 9999)
    xPlayer.addWeapon('weapon_specialcarbine', 9999)
    xPlayer.addWeapon('weapon_specialcarbine_mk2', 9999)
    xPlayer.addWeapon('weapon_bullpuprifle', 9999)
    xPlayer.addWeapon('weapon_bullpuprifle_mk2', 9999)
    xPlayer.addWeapon('weapon_compactrifle', 9999)
    xPlayer.addWeapon('weapon_militaryrifle', 9999)
    xPlayer.addWeapon('weapon_heavyrifle', 9999)
    xPlayer.addWeapon('weapon_tacticalrifle', 9999)
    -- Light Machine Guns
    xPlayer.addWeapon('weapon_mg', 9999)
    xPlayer.addWeapon('weapon_combatmg', 9999)
    xPlayer.addWeapon('weapon_combatmg_mk2', 9999)
    xPlayer.addWeapon('weapon_gusenberg', 9999)
    -- Sniper Rifles
    xPlayer.addWeapon('weapon_sniperrifle', 9999)
    xPlayer.addWeapon('weapon_heavysniper', 9999)
    xPlayer.addWeapon('weapon_heavysniper_mk2', 9999)
    xPlayer.addWeapon('weapon_marksmanrifle', 9999)
    xPlayer.addWeapon('weapon_marksmanrifle_mk2', 9999)
    xPlayer.addWeapon('weapon_precisionrifle', 9999)
    -- Heavy Weapons
    xPlayer.addWeapon('weapon_rpg', 9999)
    xPlayer.addWeapon('weapon_grenadelauncher', 9999)
    xPlayer.addWeapon('weapon_grenadelauncher_smoke', 9999)
    xPlayer.addWeapon('weapon_minigun', 9999)
    xPlayer.addWeapon('weapon_firework', 9999)
    xPlayer.addWeapon('weapon_railgun', 9999)
    xPlayer.addWeapon('weapon_hominglauncher', 9999)
    xPlayer.addWeapon('weapon_compactlauncher', 9999)
    xPlayer.addWeapon('weapon_rayminigun', 9999)
    xPlayer.addWeapon('weapon_emplauncher', 9999)
    -- Throwables
    xPlayer.addWeapon('weapon_grenade', 9999)
    xPlayer.addWeapon('weapon_bzgas', 9999)
    xPlayer.addWeapon('weapon_molotov', 9999)
    xPlayer.addWeapon('weapon_stickybomb', 9999)
    xPlayer.addWeapon('weapon_proxmine', 9999)
    xPlayer.addWeapon('weapon_snowball', 9999)
    xPlayer.addWeapon('weapon_pipebomb', 9999)
    xPlayer.addWeapon('weapon_ball', 9999)
    xPlayer.addWeapon('weapon_smokegrenade', 9999)
    xPlayer.addWeapon('weapon_flare', 9999)
    -- Miscellaneous
    xPlayer.addWeapon('weapon_petrolcan', 9999)
    xPlayer.addWeapon('gadget_parachute', 9999)
    xPlayer.addWeapon('weapon_fireextinguisher', 9999)
    xPlayer.addWeapon('weapon_hazardcan', 9999)
    xPlayer.addWeapon('weapon_fertilizercan', 9999)
    
    TriggerClientEvent('esx:showNotification', source, "| - Give d'arme effectu� ~b~avec succ�s~s~ !")
end)